name: CI

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

# Cancel old builds on new commit for same workflow + branch/PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'


      - run: |
          npm clean-install
          npm run check
          npm run test

  prettier-check:
    name: Prettier check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actionsx/prettier@v3
        with:
          args: --check "{src,test}/**/*.ts"
  
  docker:
    name: Build with docker
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repo

      - uses: docker/setup-buildx-action@v3
        name: Set up Docker Buildx
      
      - uses: docker/build-push-action@v5
        with:
          push: false
          tags: pg-meta:test
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Check Health status
        run: |
          docker run -d --name pg-meta-test pg-meta:test
          state=$(docker inspect -f '{{ .State.Health.Status}}' pg-meta-test)
          if [ $state != "starting" ]; then
            exit 1
          fi
          sleep 10
          state=$(docker inspect -f '{{ .State.Health.Status}}' pg-meta-test)
          docker stop pg-meta-test
          if [ $state == "healthy" ]; then
            exit 0
          else
            exit 1
          fi
      
      

