name: Publish Dependencies

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  publish:
    # Must match glibc verison in node:20
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
        with:
          repository: 'pyramation/libpg-query-node'
          ref: 'v15'

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - run: npm i
      - run: npm run binary:build

      - uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.PROD_AWS_ROLE }}
          aws-region: us-east-1

      - run: npx node-pre-gyp publish
